export const TEXT_TYPING_DELAY_GENERATE = 50;
export const TEXT_TYPING_DELAY_REMOVE = 30;
export const TEXT_TYPING_DELAY_BEFORE_REMOVE = 4000;
export const TEXT_TYPING_DELAY_BEFORE_GENERATE = 0;
export const TEXT_TYPING_DELAY_BEFORE_REPLAY = 0;
